apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=registry-1.docker.com/tburmaster/python-helloworld:v2
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/burmaster0/helloworld-argocd.git
    targetRevision: main
    path: helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd


  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true